### PR TITLE
Fix #80 brace bug

### LINKED ISSUE #80: one brace more
issue
there is one more brace in these code

### PR DESCRIPTION
**Pull request by xcircle**
fix brace bug in README

### CODE REVIEW

**Comment by ivy-dong** [comment]
title maybe add: Fixes #81 fix brace bug

**Comment by ivy-dong** [comment]
title maybe add ‘Fixes IssueID’ like: Fixes #81 fix brace bug

**Comment by ivy-dong** [comment]
Sorry #80

**Comment by xcircle** [comment]
done~thanks guiding

**Pull request merged**
